 <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="MyModelLabel" aria-hidden="true">
					<div class="modal-dialog" >
					<div class="modal-content">
						<div class="modal-header">	
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times;</button>
							<form action="php/validar.php" method="POST" name="adsearch" id="register"> 
          							<div class="alert-box success form-feedback"></div>
                 					<div class="register-top-grid">
					                    <label for="name">Email</label> <input name="email" id="email" type="email" required="required" />
					                    <label for="surname">Contrase&ntilde;a</label> <input name="pass" type="password" required="required" />
								      <input type="submit" name="submit_log" value="Login" class="register"  /> 
							</form>
							
						</div> 
						<div calss="modal-footer">
					

							</div>
						</div>

					</div>
						<script src="https://code.jquery.com/jquery.js"></script>
						<script src="../bootstrap/js/bootstrap.min.js"></script>
				</div>
				</div>